version: '3.8'

services:
  db:
    volumes:
      - ./sqlScript/docker:/docker-entrypoint-initdb.d
    container_name: db
    image: postgres:12.13-alpine3.17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testr
    ports: ["5430:5432"]

  backend:
      container_name: backend
      build:
        context: .
        dockerfile: /Dockerfile
      restart: always
      depends_on: [db]
      ports: ["8080:8080"]
      environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/testr
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=postgres
        - SPRING_JPA_HIBERNATE_DDL_AUTO=validate

  frontend:
      container_name: frontend
      build:
        context: frontend/react-typescript
        dockerfile: /Dockerfile
      ports: ["5500:3000"]